import { FileNode, createCodeLines } from "./code-editor";

// Shared portfolio file structure for the CodeEditor component
// Following Next.js App Router structure without src folder
export const portfolioFiles: FileNode[] = [
  {
    id: "portfolio",
    name: "portfolio",
    type: "folder",
    children: [
      {
        id: "app",
        name: "app",
        type: "folder",
        children: [
          {
            id: "layout.tsx",
            name: "layout.tsx",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">import</span> <span class="syntax-type">type</span> <span class="syntax-operator">{</span> <span class="syntax-type">Metadata</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"next"</span><span class="syntax-operator">;</span>',
              '<span class="syntax-keyword">import</span> <span class="syntax-string">"./globals.css"</span><span class="syntax-operator">;</span>',
              "",
              '<span class="syntax-keyword">export</span> <span class="syntax-keyword">const</span> <span class="syntax-variable">metadata</span><span class="syntax-operator">:</span> <span class="syntax-type">Metadata</span> <span class="syntax-operator">=</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">title</span><span class="syntax-operator">:</span> <span class="syntax-string">"Waseem Anjum | Developer"</span><span class="syntax-operator">,</span>',
              '  <span class="syntax-variable">description</span><span class="syntax-operator">:</span> <span class="syntax-string">"Full Stack Developer"</span><span class="syntax-operator">,</span>',
              '<span class="syntax-operator">};</span>',
              "",
              '<span class="syntax-keyword">export</span> <span class="syntax-keyword">default</span> <span class="syntax-keyword">function</span> <span class="syntax-function">RootLayout</span><span class="syntax-operator">({</span>',
              '  <span class="syntax-variable">children</span><span class="syntax-operator">,</span>',
              '<span class="syntax-operator">}:</span> <span class="syntax-operator">{</span> <span class="syntax-variable">children</span><span class="syntax-operator">:</span> <span class="syntax-type">React.ReactNode</span> <span class="syntax-operator">})</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-keyword">return</span> <span class="syntax-operator">(</span>',
              '    <span class="syntax-operator">&lt;</span><span class="syntax-variable">html</span> <span class="syntax-variable">lang</span><span class="syntax-operator">=</span><span class="syntax-string">"en"</span><span class="syntax-operator">&gt;</span>',
              '      <span class="syntax-operator">&lt;</span><span class="syntax-variable">body</span><span class="syntax-operator">&gt;{</span><span class="syntax-variable">children</span><span class="syntax-operator">}&lt;/</span><span class="syntax-variable">body</span><span class="syntax-operator">&gt;</span>',
              '    <span class="syntax-operator">&lt;/</span><span class="syntax-variable">html</span><span class="syntax-operator">&gt;</span>',
              '  <span class="syntax-operator">);</span>',
              '<span class="syntax-operator">}</span>',
            ]),
          },
          {
            id: "page.tsx",
            name: "page.tsx",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">import</span> <span class="syntax-operator">{</span> <span class="syntax-variable">Hero</span><span class="syntax-operator">,</span> <span class="syntax-variable">About</span><span class="syntax-operator">,</span> <span class="syntax-variable">Skills</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"@/components"</span><span class="syntax-operator">;</span>',
              "",
              '<span class="syntax-keyword">export</span> <span class="syntax-keyword">default</span> <span class="syntax-keyword">function</span> <span class="syntax-function">Home</span><span class="syntax-operator">()</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-keyword">return</span> <span class="syntax-operator">(</span>',
              '    <span class="syntax-operator">&lt;</span><span class="syntax-variable">main</span><span class="syntax-operator">&gt;</span>',
              '      <span class="syntax-operator">&lt;</span><span class="syntax-variable">Hero</span> <span class="syntax-operator">/&gt;</span>',
              '      <span class="syntax-operator">&lt;</span><span class="syntax-variable">About</span> <span class="syntax-operator">/&gt;</span>',
              '      <span class="syntax-operator">&lt;</span><span class="syntax-variable">Skills</span> <span class="syntax-operator">/&gt;</span>',
              '    <span class="syntax-operator">&lt;/</span><span class="syntax-variable">main</span><span class="syntax-operator">&gt;</span>',
              '  <span class="syntax-operator">);</span>',
              '<span class="syntax-operator">}</span>',
            ]),
          },
          {
            id: "globals.css",
            name: "globals.css",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">@import</span> <span class="syntax-string">"tailwindcss"</span><span class="syntax-operator">;</span>',
              "",
              '<span class="syntax-variable">:root</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">--background</span><span class="syntax-operator">:</span> <span class="syntax-number">0 0% 100%</span><span class="syntax-operator">;</span>',
              '  <span class="syntax-variable">--foreground</span><span class="syntax-operator">:</span> <span class="syntax-number">0 0% 3.9%</span><span class="syntax-operator">;</span>',
              '  <span class="syntax-variable">--primary</span><span class="syntax-operator">:</span> <span class="syntax-number">142 76% 36%</span><span class="syntax-operator">;</span>',
              '<span class="syntax-operator">}</span>',
            ]),
          },
          {
            id: "api",
            name: "api",
            type: "folder",
            children: [
              {
                id: "projects",
                name: "projects",
                type: "folder",
                children: [
                  {
                    id: "route.ts",
                    name: "route.ts",
                    type: "file",
                    content: createCodeLines([
                      '<span class="syntax-keyword">import</span> <span class="syntax-operator">{</span> <span class="syntax-variable">NextResponse</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"next/server"</span><span class="syntax-operator">;</span>',
                      '<span class="syntax-keyword">import</span> <span class="syntax-operator">{</span> <span class="syntax-variable">prisma</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"@/lib/prisma"</span><span class="syntax-operator">;</span>',
                      "",
                      '<span class="syntax-keyword">export</span> <span class="syntax-keyword">async</span> <span class="syntax-keyword">function</span> <span class="syntax-function">GET</span><span class="syntax-operator">()</span> <span class="syntax-operator">{</span>',
                      '  <span class="syntax-keyword">const</span> <span class="syntax-variable">projects</span> <span class="syntax-operator">=</span> <span class="syntax-keyword">await</span> <span class="syntax-variable">prisma</span><span class="syntax-operator">.</span><span class="syntax-variable">project</span><span class="syntax-operator">.</span><span class="syntax-function">findMany</span><span class="syntax-operator">();</span>',
                      '  <span class="syntax-keyword">return</span> <span class="syntax-variable">NextResponse</span><span class="syntax-operator">.</span><span class="syntax-function">json</span><span class="syntax-operator">(</span><span class="syntax-variable">projects</span><span class="syntax-operator">);</span>',
                      '<span class="syntax-operator">}</span>',
                    ]),
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "components",
        name: "components",
        type: "folder",
        children: [
          {
            id: "hero.tsx",
            name: "hero.tsx",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-string">"use client"</span><span class="syntax-operator">;</span>',
              "",
              '<span class="syntax-keyword">import</span> <span class="syntax-operator">{</span> <span class="syntax-variable">motion</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"framer-motion"</span><span class="syntax-operator">;</span>',
              "",
              '<span class="syntax-keyword">export</span> <span class="syntax-keyword">function</span> <span class="syntax-function">Hero</span><span class="syntax-operator">()</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-keyword">return</span> <span class="syntax-operator">(</span>',
              '    <span class="syntax-operator">&lt;</span><span class="syntax-variable">section</span> <span class="syntax-variable">className</span><span class="syntax-operator">=</span><span class="syntax-string">"min-h-screen"</span><span class="syntax-operator">&gt;</span>',
              '      <span class="syntax-operator">&lt;</span><span class="syntax-variable">motion.h1</span> <span class="syntax-variable">animate</span><span class="syntax-operator">={{ </span><span class="syntax-variable">opacity</span><span class="syntax-operator">:</span> <span class="syntax-number">1</span> <span class="syntax-operator">}}&gt;</span>',
              '        <span class="syntax-string">Hello, I\'m Waseem</span>',
              '      <span class="syntax-operator">&lt;/</span><span class="syntax-variable">motion.h1</span><span class="syntax-operator">&gt;</span>',
              '    <span class="syntax-operator">&lt;/</span><span class="syntax-variable">section</span><span class="syntax-operator">&gt;</span>',
              '  <span class="syntax-operator">);</span>',
              '<span class="syntax-operator">}</span>',
            ]),
          },
          {
            id: "about.tsx",
            name: "about.tsx",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-comment">// About Me - The Developer Behind the Code</span>',
              "",
              '<span class="syntax-keyword">class</span> <span class="syntax-type">Developer</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-function">constructor</span><span class="syntax-operator">() {</span>',
              '    <span class="syntax-keyword">this</span><span class="syntax-operator">.</span><span class="syntax-variable">name</span> <span class="syntax-operator">=</span> <span class="syntax-string">"Waseem Anjum"</span><span class="syntax-operator">;</span>',
              '    <span class="syntax-keyword">this</span><span class="syntax-operator">.</span><span class="syntax-variable">title</span> <span class="syntax-operator">=</span> <span class="syntax-string">"Full Stack & Web3 Developer"</span><span class="syntax-operator">;</span>',
              '    <span class="syntax-keyword">this</span><span class="syntax-operator">.</span><span class="syntax-variable">location</span> <span class="syntax-operator">=</span> <span class="syntax-string">"Building the future"</span><span class="syntax-operator">;</span>',
              '  <span class="syntax-operator">}</span>',
              "",
              '  <span class="syntax-function">getSkillset</span><span class="syntax-operator">() {</span>',
              '    <span class="syntax-keyword">return</span> <span class="syntax-operator">{</span>',
              '      <span class="syntax-variable">languages</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"TypeScript"</span><span class="syntax-operator">,</span> <span class="syntax-string">"JavaScript"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Solidity"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Python"</span><span class="syntax-operator">],</span>',
              '      <span class="syntax-variable">frontend</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"React"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Next.js"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Tailwind"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Web3.js"</span><span class="syntax-operator">],</span>',
              '      <span class="syntax-variable">backend</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"Node.js"</span><span class="syntax-operator">,</span> <span class="syntax-string">"PostgreSQL"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Prisma"</span><span class="syntax-operator">],</span>',
              '      <span class="syntax-variable">web3</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"Ethereum"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Smart Contracts"</span><span class="syntax-operator">,</span> <span class="syntax-string">"DApp Development"</span><span class="syntax-operator">],</span>',
              '      <span class="syntax-variable">tools</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"Git"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Docker"</span><span class="syntax-operator">,</span> <span class="syntax-string">"AWS"</span><span class="syntax-operator">]</span>',
              '    <span class="syntax-operator">};</span>',
              '  <span class="syntax-operator">}</span>',
              "",
              '  <span class="syntax-function">getCurrentFocus</span><span class="syntax-operator">() {</span>',
              '    <span class="syntax-keyword">return</span> <span class="syntax-operator">[</span>',
              '      <span class="syntax-string">"Building scalable web apps"</span><span class="syntax-operator">,</span>',
              '      <span class="syntax-string">"Creating DApps & Web3 products"</span><span class="syntax-operator">,</span>',
              '      <span class="syntax-string">"Writing clean code"</span>',
              '    <span class="syntax-operator">];</span>',
              '  <span class="syntax-operator">}</span>',
              '<span class="syntax-operator">}</span>',
            ]),
          },
          {
            id: "skills.tsx",
            name: "skills.tsx",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">const</span> <span class="syntax-variable">skills</span> <span class="syntax-operator">=</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">frontend</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"React / Next.js"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">95</span> <span class="syntax-operator">},</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"TypeScript"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">90</span> <span class="syntax-operator">},</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"Tailwind CSS"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">95</span> <span class="syntax-operator">},</span>',
              '  <span class="syntax-operator">],</span>',
              '  <span class="syntax-variable">backend</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"Node.js"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">90</span> <span class="syntax-operator">},</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"PostgreSQL"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">85</span> <span class="syntax-operator">},</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"REST APIs"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">95</span> <span class="syntax-operator">},</span>',
              '  <span class="syntax-operator">],</span>',
              '  <span class="syntax-variable">tools</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"Git / GitHub"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">95</span> <span class="syntax-operator">},</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"Docker"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">80</span> <span class="syntax-operator">},</span>',
              '    <span class="syntax-operator">{</span> <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"AWS"</span><span class="syntax-operator">,</span> <span class="syntax-variable">level</span><span class="syntax-operator">:</span> <span class="syntax-number">75</span> <span class="syntax-operator">},</span>',
              '  <span class="syntax-operator">]</span>',
              '<span class="syntax-operator">};</span>',
            ]),
          },
          {
            id: "projects.tsx",
            name: "projects.tsx",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">interface</span> <span class="syntax-type">Project</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-type">string</span><span class="syntax-operator">;</span>',
              '  <span class="syntax-variable">description</span><span class="syntax-operator">:</span> <span class="syntax-type">string</span><span class="syntax-operator">;</span>',
              '  <span class="syntax-variable">tech</span><span class="syntax-operator">:</span> <span class="syntax-type">string</span><span class="syntax-operator">[];</span>',
              '  <span class="syntax-variable">url</span><span class="syntax-operator">:</span> <span class="syntax-type">string</span><span class="syntax-operator">;</span>',
              '  <span class="syntax-variable">featured</span><span class="syntax-operator">:</span> <span class="syntax-type">boolean</span><span class="syntax-operator">;</span>',
              '<span class="syntax-operator">}</span>',
              "",
              '<span class="syntax-keyword">const</span> <span class="syntax-variable">projects</span><span class="syntax-operator">:</span> <span class="syntax-type">Project</span><span class="syntax-operator">[] =</span> <span class="syntax-operator">[</span>',
              '  <span class="syntax-operator">{</span>',
              '    <span class="syntax-variable">name</span><span class="syntax-operator">:</span> <span class="syntax-string">"E-Commerce Platform"</span><span class="syntax-operator">,</span>',
              '    <span class="syntax-variable">tech</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"Next.js"</span><span class="syntax-operator">,</span> <span class="syntax-string">"Stripe"</span><span class="syntax-operator">],</span>',
              '    <span class="syntax-variable">featured</span><span class="syntax-operator">:</span> <span class="syntax-keyword">true</span>',
              '  <span class="syntax-operator">}</span>',
              '<span class="syntax-operator">];</span>',
            ]),
          },
          {
            id: "experience.tsx",
            name: "experience.tsx",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">const</span> <span class="syntax-variable">experience</span> <span class="syntax-operator">=</span> <span class="syntax-operator">[</span>',
              '  <span class="syntax-operator">{</span>',
              '    <span class="syntax-variable">role</span><span class="syntax-operator">:</span> <span class="syntax-string">"Senior Full Stack Developer"</span><span class="syntax-operator">,</span>',
              '    <span class="syntax-variable">company</span><span class="syntax-operator">:</span> <span class="syntax-string">"Tech Innovations Inc"</span><span class="syntax-operator">,</span>',
              '    <span class="syntax-variable">period</span><span class="syntax-operator">:</span> <span class="syntax-string">"2022 - Present"</span><span class="syntax-operator">,</span>',
              '    <span class="syntax-variable">highlights</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span>',
              '      <span class="syntax-string">"Led development of scalable apps"</span><span class="syntax-operator">,</span>',
              '      <span class="syntax-string">"Reduced load time by 60%"</span><span class="syntax-operator">,</span>',
              '      <span class="syntax-string">"Mentored junior developers"</span>',
              '    <span class="syntax-operator">]</span>',
              '  <span class="syntax-operator">},</span>',
              '  <span class="syntax-operator">{</span>',
              '    <span class="syntax-variable">role</span><span class="syntax-operator">:</span> <span class="syntax-string">"Full Stack Developer"</span><span class="syntax-operator">,</span>',
              '    <span class="syntax-variable">company</span><span class="syntax-operator">:</span> <span class="syntax-string">"Digital Solutions Co"</span><span class="syntax-operator">,</span>',
              '    <span class="syntax-variable">period</span><span class="syntax-operator">:</span> <span class="syntax-string">"2020 - 2022"</span>',
              '  <span class="syntax-operator">}</span>',
              '<span class="syntax-operator">];</span>',
            ]),
          },
        ],
      },
      {
        id: "lib",
        name: "lib",
        type: "folder",
        children: [
          {
            id: "prisma.ts",
            name: "prisma.ts",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">import</span> <span class="syntax-operator">{</span> <span class="syntax-type">PrismaClient</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"@prisma/client"</span><span class="syntax-operator">;</span>',
              "",
              '<span class="syntax-keyword">const</span> <span class="syntax-variable">globalForPrisma</span> <span class="syntax-operator">=</span> <span class="syntax-variable">global</span> <span class="syntax-keyword">as</span> <span class="syntax-type">unknown</span> <span class="syntax-keyword">as</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">prisma</span><span class="syntax-operator">:</span> <span class="syntax-type">PrismaClient</span> <span class="syntax-operator">|</span> <span class="syntax-type">undefined</span>',
              '<span class="syntax-operator">};</span>',
              "",
              '<span class="syntax-keyword">export</span> <span class="syntax-keyword">const</span> <span class="syntax-variable">prisma</span> <span class="syntax-operator">=</span>',
              '  <span class="syntax-variable">globalForPrisma</span><span class="syntax-operator">.</span><span class="syntax-variable">prisma</span> <span class="syntax-operator">??</span> <span class="syntax-keyword">new</span> <span class="syntax-type">PrismaClient</span><span class="syntax-operator">();</span>',
            ]),
          },
          {
            id: "utils.ts",
            name: "utils.ts",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">import</span> <span class="syntax-operator">{</span> <span class="syntax-variable">clsx</span><span class="syntax-operator">,</span> <span class="syntax-type">ClassValue</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"clsx"</span><span class="syntax-operator">;</span>',
              '<span class="syntax-keyword">import</span> <span class="syntax-operator">{</span> <span class="syntax-variable">twMerge</span> <span class="syntax-operator">}</span> <span class="syntax-keyword">from</span> <span class="syntax-string">"tailwind-merge"</span><span class="syntax-operator">;</span>',
              "",
              '<span class="syntax-keyword">export</span> <span class="syntax-keyword">function</span> <span class="syntax-function">cn</span><span class="syntax-operator">(...</span><span class="syntax-variable">inputs</span><span class="syntax-operator">:</span> <span class="syntax-type">ClassValue</span><span class="syntax-operator">[])</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-keyword">return</span> <span class="syntax-function">twMerge</span><span class="syntax-operator">(</span><span class="syntax-function">clsx</span><span class="syntax-operator">(</span><span class="syntax-variable">inputs</span><span class="syntax-operator">));</span>',
              '<span class="syntax-operator">}</span>',
            ]),
          },
        ],
      },
      {
        id: "prisma",
        name: "prisma",
        type: "folder",
        children: [
          {
            id: "schema.prisma",
            name: "schema.prisma",
            type: "file",
            content: createCodeLines([
              '<span class="syntax-keyword">generator</span> <span class="syntax-variable">client</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">provider</span> <span class="syntax-operator">=</span> <span class="syntax-string">"prisma-client-js"</span>',
              '<span class="syntax-operator">}</span>',
              "",
              '<span class="syntax-keyword">datasource</span> <span class="syntax-variable">db</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">provider</span> <span class="syntax-operator">=</span> <span class="syntax-string">"postgresql"</span>',
              '  <span class="syntax-variable">url</span> <span class="syntax-operator">=</span> <span class="syntax-function">env</span><span class="syntax-operator">(</span><span class="syntax-string">"DATABASE_URL"</span><span class="syntax-operator">)</span>',
              '<span class="syntax-operator">}</span>',
              "",
              '<span class="syntax-keyword">model</span> <span class="syntax-type">Project</span> <span class="syntax-operator">{</span>',
              '  <span class="syntax-variable">id</span>          <span class="syntax-type">String</span>   <span class="syntax-keyword">@id</span> <span class="syntax-keyword">@default</span><span class="syntax-operator">(</span><span class="syntax-function">cuid</span><span class="syntax-operator">())</span>',
              '  <span class="syntax-variable">title</span>       <span class="syntax-type">String</span>',
              '  <span class="syntax-variable">description</span> <span class="syntax-type">String</span><span class="syntax-operator">?</span>',
              '  <span class="syntax-variable">createdAt</span>   <span class="syntax-type">DateTime</span> <span class="syntax-keyword">@default</span><span class="syntax-operator">(</span><span class="syntax-function">now</span><span class="syntax-operator">())</span>',
              '<span class="syntax-operator">}</span>',
            ]),
          },
        ],
      },
      {
        id: "package.json",
        name: "package.json",
        type: "file",
        content: createCodeLines([
          '<span class="syntax-operator">{</span>',
          '  <span class="syntax-variable">"name"</span><span class="syntax-operator">:</span> <span class="syntax-string">"portfolio"</span><span class="syntax-operator">,</span>',
          '  <span class="syntax-variable">"version"</span><span class="syntax-operator">:</span> <span class="syntax-string">"1.0.0"</span><span class="syntax-operator">,</span>',
          '  <span class="syntax-variable">"dependencies"</span><span class="syntax-operator">:</span> <span class="syntax-operator">{</span>',
          '    <span class="syntax-variable">"react"</span><span class="syntax-operator">:</span> <span class="syntax-string">"^19.0.0"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"next"</span><span class="syntax-operator">:</span> <span class="syntax-string">"^16.0.0"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"typescript"</span><span class="syntax-operator">:</span> <span class="syntax-string">"^5.0.0"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"tailwindcss"</span><span class="syntax-operator">:</span> <span class="syntax-string">"^4.0.0"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"prisma"</span><span class="syntax-operator">:</span> <span class="syntax-string">"^7.0.0"</span>',
          '  <span class="syntax-operator">},</span>',
          '  <span class="syntax-variable">"scripts"</span><span class="syntax-operator">:</span> <span class="syntax-operator">{</span>',
          '    <span class="syntax-variable">"dev"</span><span class="syntax-operator">:</span> <span class="syntax-string">"next dev --turbopack"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"build"</span><span class="syntax-operator">:</span> <span class="syntax-string">"next build"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"start"</span><span class="syntax-operator">:</span> <span class="syntax-string">"next start"</span>',
          '  <span class="syntax-operator">}</span>',
          '<span class="syntax-operator">}</span>',
        ]),
      },
      {
        id: "tsconfig.json",
        name: "tsconfig.json",
        type: "file",
        content: createCodeLines([
          '<span class="syntax-operator">{</span>',
          '  <span class="syntax-variable">"compilerOptions"</span><span class="syntax-operator">:</span> <span class="syntax-operator">{</span>',
          '    <span class="syntax-variable">"target"</span><span class="syntax-operator">:</span> <span class="syntax-string">"ES2022"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"lib"</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"dom"</span><span class="syntax-operator">,</span> <span class="syntax-string">"ES2022"</span><span class="syntax-operator">],</span>',
          '    <span class="syntax-variable">"strict"</span><span class="syntax-operator">:</span> <span class="syntax-keyword">true</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"jsx"</span><span class="syntax-operator">:</span> <span class="syntax-string">"preserve"</span><span class="syntax-operator">,</span>',
          '    <span class="syntax-variable">"paths"</span><span class="syntax-operator">:</span> <span class="syntax-operator">{</span>',
          '      <span class="syntax-variable">"@/*"</span><span class="syntax-operator">:</span> <span class="syntax-operator">[</span><span class="syntax-string">"./*"</span><span class="syntax-operator">]</span>',
          '    <span class="syntax-operator">}</span>',
          '  <span class="syntax-operator">}</span>',
          '<span class="syntax-operator">}</span>',
        ]),
      },
      {
        id: "README.md",
        name: "README.md",
        type: "file",
        content: createCodeLines([
          '<span class="syntax-comment"># Portfolio</span>',
          "",
          '<span class="syntax-variable">A modern portfolio built with:</span>',
          "",
          '<span class="syntax-operator">-</span> <span class="syntax-string">Next.js 16</span>',
          '<span class="syntax-operator">-</span> <span class="syntax-string">TypeScript</span>',
          '<span class="syntax-operator">-</span> <span class="syntax-string">Tailwind CSS v4</span>',
          '<span class="syntax-operator">-</span> <span class="syntax-string">Framer Motion</span>',
          "",
          '<span class="syntax-comment">## Getting Started</span>',
          "",
          '<span class="syntax-keyword">npm</span> <span class="syntax-variable">install</span>',
          '<span class="syntax-keyword">npm</span> <span class="syntax-variable">run dev</span>',
        ]),
      },
    ],
  },
];
